[package]
name = "day03_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
puzzle_inputs = {path = "../puzzle_inputs"}
ndarray = "0.15.4"